# Generated by Django 3.0.4 on 2020-03-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('ptype', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('stock', models.IntegerField()),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='products/pics')),
                ('offer', models.BooleanField(default=False)),
                ('offerprice', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('userid', models.CharField(max_length=100)),
            ],
        ),
    ]
