# Generated by Django 3.0.4 on 2020-03-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0004_auto_20200310_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ptype',
            field=models.CharField(choices=[('Vegetables', 'Vegetables'), ('Products', 'Products'), ('Dried', 'Dried'), ('Fruits', 'Fruits')], default='Vegetables', max_length=10),
        ),
    ]
