# Generated by Django 3.0.4 on 2020-03-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0010_auto_20200311_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
