# Generated by Django 3.0.4 on 2020-03-15 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmers', '0011_products_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='farmers/pics')),
                ('isactive', models.BooleanField(default=True)),
                ('license_no', models.CharField(max_length=20)),
                ('manufacture_code', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
