# Generated by Django 3.0.4 on 2020-03-16 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0012_farmers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='farmers',
        ),
    ]
