# Generated by Django 3.0.4 on 2020-03-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(default=None, upload_to='farmers/pics'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ismerchant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='license_no',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manufacture_code',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
