# Generated by Django 3.0.4 on 2020-03-16 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_auto_20200316_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
    ]
