# Generated by Django 3.0.4 on 2020-03-17 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0013_delete_farmers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public', '0008_remove_userprofile_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('productid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='farmers.products')),
                ('userid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
